# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [], stdenv}:

let
  rawSources = {
    "@babel/helper-validator-identifier-7.10.4" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.10.4.tgz";
        sha512 = "3U9y+43hz7ZM+rzG24Qe2mufW5KhvFg/NhnNph+i9mgCtdTCtMJuI1TMkrIUiK7Ix4PYlRF9I5dhqaLYA/ADXw==";
      };
    };
    "@babel/highlight-7.10.4" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.10.4.tgz";
        sha512 = "i6rgnR/YgPEQzZZnbTHHuZdlE8qyoBNalD6F+q4vAFlcMEcqmkoG+mPqJYJCo63qPf74+Y1UZsl3l6f7/RIkmA==";
      };
    };
    "@babel/runtime-7.9.2" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.9.2.tgz";
        sha512 = "NE2DtOdufG7R5vnfQUTehdTfNycfUANEtCa9PssN9O/xmTzP4E08UI797ixaei6hBEVL9BI/PsdJS5x7mWoB9Q==";
      };
    };
    "agent-base-6.0.1" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.1.tgz";
        sha512 = "01q25QQDwLSsyfhrKbn8yuur+JNw0H+0Y4JiGIKd3z9aYk/w/2kxD/Upc+t2ZBBSUNff50VjPsSW2YxM8QYKVg==";
      };
    };
    "ansi-regex-4.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.0.tgz";
        sha512 = "1apePfXM1UOSqw0o9IiFAovVz9M5S1Dg+4TrDwfMewQ6p/rmMueb7tWZjQ1rx4Loy1ArBggoqGpfqqdI4rondg==";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "ansi-styles-4.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.2.1.tgz";
        sha512 = "9VGjrMsG1vePxcSweQsN20KY/c4zN0h9fLjqAbwbPfahM3t+NL+M9HC8xeXG2I8pX5NoamTGNuomEUFI7fcUjA==";
      };
    };
    "ast-types-0.11.7" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.11.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.11.7.tgz";
        sha512 = "2mP3TwtkY/aTv5X3ZsMpNAbOnyoC/aMJwJSoaELPkHId0nSQgFcnU4dRW3isxiz7+zBexk0ym3WNVjMiQBnJSw==";
      };
    };
    "bn.js-5.1.2" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.1.2.tgz";
        sha512 = "40rZaf3bUNKTVYu9sIeeEGOg7g14Yvnj9kH7b50EiwX0Q7A6umbvfI5tvHaOERH0XigqKkfLkFQxzb4e6CIXnA==";
      };
    };
    "chalk-4.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz";
        sha512 = "qwx12AxXe2Q5xQ43Ac//I6v5aXTipYrSESdOgzrN+9XjgEpyjpKuvSGaN4qE93f7TQTlerQQ8S+EQ0EyDoVL1A==";
      };
    };
    "classnames-2.2.6" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.6.tgz";
        sha512 = "JR/iSQOSt+LQIWwrwEzJ9uk0xfN3mTVYMwt1Ir5mUcSN6pU+V4zQFFaJsclJbPuAUQH+yfWef6tm7l1quW3C8Q==";
      };
    };
    "cli-width-3.0.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-3.0.0.tgz";
        sha512 = "FxqpkPPwu1HjuN93Omfm4h8uIanXofW0RxVEW3k5RKx+mJJYSthzNhp32Kzxxy3YAEZ/Dc/EWN1vZRY0+kOhbw==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "copy-to-clipboard-3.3.1" = {
      name = "copy-to-clipboard";
      packageName = "copy-to-clipboard";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-to-clipboard/-/copy-to-clipboard-3.3.1.tgz";
        sha512 = "i13qo6kIHTTpCm8/Wup+0b1mVWETvu2kIMzKoK8FpkLkFxlt0znUAHcMzox+T8sPlqtZXq3CulEjQHsYiGFJUw==";
      };
    };
    "date-fns-1.30.1" = {
      name = "date-fns";
      packageName = "date-fns";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-fns/-/date-fns-1.30.1.tgz";
        sha512 = "hBSVCvSmWC+QypYObzwGOd9wqdDpOt+0wl0KbU+R+uuZBS1jN8VsD1ss3irQDknRj5NvxiTF6oj/nDRnN/UQNw==";
      };
    };
    "deep-diff-0.3.8" = {
      name = "deep-diff";
      packageName = "deep-diff";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-diff/-/deep-diff-0.3.8.tgz";
        sha1 = "c01de63efb0eec9798801d40c7e0dae25b582c84";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "envify-4.1.0" = {
      name = "envify";
      packageName = "envify";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/envify/-/envify-4.1.0.tgz";
        sha512 = "IKRVVoAYr4pIx4yIWNsz9mOsboxlNXiu7TNBnem/K/uTHdkyzXWDzHCK7UTolqBbgaBz0tQHsD3YNls0uIIjiw==";
      };
    };
    "es6-promisify-5.0.0" = {
      name = "es6-promisify";
      packageName = "es6-promisify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz";
        sha1 = "5109d62f3e56ea967c4b63505aef08291c8a5203";
      };
    };
    "eslint-config-standard-14.1.1" = {
      name = "eslint-config-standard";
      packageName = "eslint-config-standard";
      version = "14.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-config-standard/-/eslint-config-standard-14.1.1.tgz";
        sha512 = "Z9B+VR+JIXRxz21udPTL9HpFMyoMUEeX1G251EQ6e05WD9aPVtVBn09XUmZ259wCMlCDmYDSZG62Hhm+ZTJcUg==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "https-proxy-agent-5.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz";
        sha512 = "EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==";
      };
    };
    "inquirer-7.3.2" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "7.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-7.3.2.tgz";
        sha512 = "DF4osh1FM6l0RJc5YWYhSDB6TawiBRlbV9Cox8MWlidU218Tb7fm3lQTULyUJDfJ0tjbzl0W4q651mrCCEM55w==";
      };
    };
    "is-callable-1.2.0" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.0.tgz";
        sha512 = "pyVD9AaGLxtg6srb2Ng6ynWJqkHU9bEM087AKck0w8QwDarTfNcpIYoU8x8Hv2Icm8u6kFJM18Dag8lyqGkviw==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-regex-1.1.0" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.0.tgz";
        sha512 = "iI97M8KTWID2la5uYXlkbSDQIg4F6o1sYboZKKTDpnDQMLtUL86zxhgDet3Q2SriaYsyGqZ6Mn2SjbRKeLHdqw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.14.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.0.tgz";
        sha512 = "/4IbIeHcD9VMHFqDR/gQ7EdZdLimOvW2DdcxFjdyyZ9NsbS+ccrXqVWDtab/lRl5AlUqmpBx8EhPaWR+OtY17A==";
      };
    };
    "jscodeshift-0.6.4" = {
      name = "jscodeshift";
      packageName = "jscodeshift";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/jscodeshift/-/jscodeshift-0.6.4.tgz";
        sha512 = "+NF/tlNbc2WEhXUuc4WEJLsJumF84tnaMUZW2hyJw3jThKKRvsPX4sPJVgO1lPE28z0gNL+gwniLG9d8mYvQCQ==";
      };
    };
    "json5-2.1.2" = {
      name = "json5";
      packageName = "json5";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.1.2.tgz";
        sha512 = "MoUOQ4WdiN3yxhm7NEVJSJrieAo5hNSLQ5sj05OTRHPL9HOBy8u4Bu88jsC1jvqAdN+E1bJmsUcZH+1HQxliqQ==";
      };
    };
    "jsx-ast-utils-2.4.1" = {
      name = "jsx-ast-utils";
      packageName = "jsx-ast-utils";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsx-ast-utils/-/jsx-ast-utils-2.4.1.tgz";
        sha512 = "z1xSldJ6imESSzOjd3NNkieVJKRlKYSOtMG8SFyCj2FIrvSaSuli/WjpBkEzCBoR9bYYYFgqJw61Xhu7Lcgk+w==";
      };
    };
    "load-json-file-2.0.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-2.0.0.tgz";
        sha1 = "7947e42149af80d696cbf797bcaabcfe1fe29ca8";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "mime-2.4.6" = {
      name = "mime";
      packageName = "mime";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.4.6.tgz";
        sha512 = "RZKhC3EmpBchfTGBVb8fb+RL2cWyw/32lshnsETttkBAyAUXSGHxbEJWWRXc751DrIxG1q04b8QwMbAwkRPpUA==";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.8.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.8.0.tgz";
        sha512 = "jLdtEOB112fORuypAyl/50VRVIBIdVQOSUUGQHzJ4xBSbit81zRarz7GThkEFZy1RceYrWYcPcBFPQwHyAc1gA==";
      };
    };
    "object.entries-1.1.2" = {
      name = "object.entries";
      packageName = "object.entries";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.entries/-/object.entries-1.1.2.tgz";
        sha512 = "BQdB9qKmb/HyNdMNWVr7O3+z5MUIx3aiegEIJqjMBbBf0YT9RRxTJSim4mzFqtyr7PDAHigq0N9dO0m0tRakQA==";
      };
    };
    "offen-../packages" = {
      name = "offen";
      packageName = "offen";
      version = 1;
      src = ../packages;
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "path-type-2.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-2.0.0.tgz";
        sha1 = "f012ccb8415b7096fc2daa1054c3d72389594c73";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "plotly.js-basic-dist-1.53.0" = {
      name = "plotly.js-basic-dist";
      packageName = "plotly.js-basic-dist";
      version = "1.53.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/plotly.js-basic-dist/-/plotly.js-basic-dist-1.53.0.tgz";
        sha512 = "906O6cwy+D8rygaYiP/ujl6PaLrEXkgwnuiNjjYnkCUfpkfd2QQEQaoRp4W9WAFFDJofbnWPOVIso7P5y1Xwtw==";
      };
    };
    "preact-10.3.4" = {
      name = "preact";
      packageName = "preact";
      version = "10.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/preact/-/preact-10.3.4.tgz";
        sha512 = "wMgzs/RGYf0I1PZf8ZFJdyU/3kCcwepJyVYe+N9FGajyQWarMoPrPfrQajcG0psPj6ySYv2cSuLYFCihvV/Qrw==";
      };
    };
    "preact-router-3.2.1" = {
      name = "preact-router";
      packageName = "preact-router";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/preact-router/-/preact-router-3.2.1.tgz";
        sha512 = "KEN2VN1DxUlTwzW5IFkF13YIA2OdQ2OvgJTkQREF+AA2NrHRLaGbB68EjS4IeZOa1shvQ1FvEm3bSLta4sXBhg==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "react-copy-to-clipboard-5.0.2" = {
      name = "react-copy-to-clipboard";
      packageName = "react-copy-to-clipboard";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-copy-to-clipboard/-/react-copy-to-clipboard-5.0.2.tgz";
        sha512 = "/2t5mLMMPuN5GmdXo6TebFa8IoFxZ+KTDDqYhcDm0PhkgEzSxVvIX26G20s1EB02A4h2UZgwtfymZ3lGJm0OLg==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-plotly.js-2.4.0" = {
      name = "react-plotly.js";
      packageName = "react-plotly.js";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-plotly.js/-/react-plotly.js-2.4.0.tgz";
        sha512 = "BCkxMe8yWqu3nP/hw9A1KCIuoL67WV5/k68SL9yhEkF6UG+pAuIev9Q3cMKtNkQJZhsYFpOmlqrpPjIdUFACOQ==";
      };
    };
    "react-redux-7.2.0" = {
      name = "react-redux";
      packageName = "react-redux";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-redux/-/react-redux-7.2.0.tgz";
        sha512 = "EvCAZYGfOLqwV7gh849xy9/pt55rJXPwmYvI4lilPM5rUT/1NxuuN59ipdBksRVSvz0KInbPnp4IfoXJXCqiDA==";
      };
    };
    "read-pkg-2.0.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-2.0.0.tgz";
        sha1 = "8ef1c0623c6a6db0dc6713c4bfac46332b2368f8";
      };
    };
    "read-pkg-up-2.0.0" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-2.0.0.tgz";
        sha1 = "6b72a8048984e0c41e79510fd5e9fa99b3b549be";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "recast-0.16.2" = {
      name = "recast";
      packageName = "recast";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/recast/-/recast-0.16.2.tgz";
        sha512 = "O/7qXi51DPjRVdbrpNzoBQH5dnAPQNbfoOFyRiUwreTMJfIHYOEBzwuH+c0+/BTSJ3CQyKs6ILSWXhESH6Op3A==";
      };
    };
    "redux-4.0.5" = {
      name = "redux";
      packageName = "redux";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-4.0.5.tgz";
        sha512 = "VSz1uMAH24DM6MF72vcojpYPtrTUu3ByVWfPL1nPfVRb5mZVTve5GnNCUV53QM/BZ66xfWrm0CTWoM+Xlz8V1w==";
      };
    };
    "redux-logger-3.0.6" = {
      name = "redux-logger";
      packageName = "redux-logger";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-logger/-/redux-logger-3.0.6.tgz";
        sha1 = "f7555966f3098f3c88604c449cf0baf5778274bf";
      };
    };
    "redux-thunk-2.3.0" = {
      name = "redux-thunk";
      packageName = "redux-thunk";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-thunk/-/redux-thunk-2.3.0.tgz";
        sha512 = "km6dclyFnmcvxhAcrQV2AkZmPQjzPDjgVlQtR0EQjxZPyJ0BnMf3in1ryuR8A2qU0HldVRfxYXbFSKlI3N7Slw==";
      };
    };
    "regenerator-runtime-0.13.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.5.tgz";
        sha512 = "ZS5w8CpKFinUzOwW3c83oPeVXoNsrLsaCoLtJvAClH135j/R77RuymhiSErhm2lKcwSCIpmvIWSbDkIfAqKQlA==";
      };
    };
    "rxjs-6.6.0" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.6.0.tgz";
        sha512 = "3HMA8z/Oz61DUHe+SdOiQyzIf4tOx5oQHmMir7IZEu6TMqCLHT4LRcmNaUS0NwOz8VLvmmBduMsoaUvMaIiqzg==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "stream-http-3.1.1" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-3.1.1.tgz";
        sha512 = "S7OqaYu0EkFpgeGFb/NPOoPLxFko7TPqtEeFg5DXPB4v/KETHG0Ln6fRFrNezoelpaDKmycEmmZ81cC9DAwgYg==";
      };
    };
    "string-width-4.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.0.tgz";
        sha512 = "zUz5JD+tgqtuDjMhwIg5uFVV3dtqZ9yQJlZVfq4I01/K5Paj5UHj7VyrQOJvzawSVlKpObApbfD0Ed6yJc+1eg==";
      };
    };
    "strip-ansi-0.3.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.3.0.tgz";
        sha1 = "25f48ea22ca79187f3174a4db8759347bb126220";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha1 = "2334c18e9c759f7bdd56fdef7e9ae3d588e68ed3";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "supports-color-7.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.1.0.tgz";
        sha512 = "oRSIpR8pxT1Wr2FquTNnGet79b3BWljqOuoW/h4oBhxJ/HUbX5nX6JSruTkvXDCFMwDPvsaTTbvMLKZWSy0R5g==";
      };
    };
    "symbol-observable-1.2.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz";
        sha512 = "e900nM8RRtGhlV36KGEU9k65K3mPb1WV70OdjfxlG2EAuM1noi/E/BaW/uMhL7bPEssK8QV57vN3esixjUvcXQ==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "toggle-selection-1.0.6" = {
      name = "toggle-selection";
      packageName = "toggle-selection";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/toggle-selection/-/toggle-selection-1.0.6.tgz";
        sha1 = "6e45b1263f2017fa0acc7d89d78b15b8bf77da32";
      };
    };
    "underscore-1.10.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.10.2.tgz";
        sha512 = "N4P+Q/BuyuEKFJ43B9gYuOj4TQUHXX+j2FqguVOpjkssLUUrnJofCcBccJSCoeturDoZU6GorDTHSvUDlSQbTg==";
      };
    };
    "url-polyfill-1.1.8" = {
      name = "url-polyfill";
      packageName = "url-polyfill";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-polyfill/-/url-polyfill-1.1.8.tgz";
        sha512 = "Ey61F4FEqhcu1vHSOMmjl0Vd/RPRLEjMj402qszD/dhMBrVfoUsnIj8KSZo2yj+eIlxJGKFdnm6ES+7UzMgZ3Q==";
      };
    };
    "v8-compile-cache-2.1.1" = {
      name = "v8-compile-cache";
      packageName = "v8-compile-cache";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache/-/v8-compile-cache-2.1.1.tgz";
        sha512 = "8OQ9CL+VWyt3JStj7HX7/ciTL2V3Rl1Wf5OL+SNTm0yK1KvtReVulksyeRnCANHHuUxHlQig+JJDlUhBt1NQDQ==";
      };
    };
    "zxcvbn-4.4.2" = {
      name = "zxcvbn";
      packageName = "zxcvbn";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/zxcvbn/-/zxcvbn-4.4.2.tgz";
        sha1 = "28ec17cf09743edcab056ddd8b1b06262cc73c30";
      };
    };
  };
  args = {sources, extraArgs}: {
    name = "auditorium";
    packageName = "auditorium";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.9.2"
      sources."classnames-2.2.6"
      sources."copy-to-clipboard-3.3.1"
      sources."date-fns-1.30.1"
      sources."deep-diff-0.3.8"
      sources."hoist-non-react-statics-3.3.2"
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      (sources."offen-../packages" // {
        dependencies = [
          sources."@babel/helper-validator-identifier-7.10.4"
          sources."@babel/highlight-7.10.4"
          sources."agent-base-6.0.1"
          sources."ast-types-0.11.7"
          sources."bn.js-5.1.2"
          sources."cli-width-3.0.0"
          sources."deep-equal-1.0.1"
          sources."envify-4.1.0"
          sources."es6-promisify-5.0.0"
          sources."eslint-config-standard-14.1.1"
          sources."esprima-4.0.1"
          sources."https-proxy-agent-5.0.0"
          (sources."inquirer-7.3.2" // {
            dependencies = [
              sources."ansi-regex-5.0.0"
              sources."ansi-styles-4.2.1"
              sources."chalk-4.1.0"
              sources."color-convert-2.0.1"
              sources."color-name-1.1.4"
              sources."has-flag-4.0.0"
              sources."strip-ansi-6.0.0"
              sources."supports-color-7.1.0"
            ];
          })
          sources."is-callable-1.2.0"
          sources."is-fullwidth-code-point-3.0.0"
          sources."is-regex-1.1.0"
          sources."js-yaml-3.14.0"
          sources."jscodeshift-0.6.4"
          sources."json5-2.1.2"
          sources."jsx-ast-utils-2.4.1"
          (sources."load-json-file-2.0.0" // {
            dependencies = [
              sources."pify-2.3.0"
            ];
          })
          sources."mime-2.4.6"
          sources."normalize-path-2.1.1"
          sources."object-inspect-1.8.0"
          sources."object.entries-1.1.2"
          sources."punycode-2.1.1"
          (sources."read-pkg-2.0.0" // {
            dependencies = [
              sources."path-type-2.0.0"
              sources."pify-2.3.0"
            ];
          })
          (sources."read-pkg-up-2.0.0" // {
            dependencies = [
              sources."find-up-2.1.0"
              sources."locate-path-2.0.0"
              sources."p-limit-1.3.0"
              sources."p-locate-2.0.0"
              sources."p-try-1.0.0"
            ];
          })
          (sources."recast-0.16.2" // {
            dependencies = [
              sources."source-map-0.6.1"
            ];
          })
          sources."rxjs-6.6.0"
          sources."semver-6.3.0"
          (sources."stream-http-3.1.1" // {
            dependencies = [
              sources."readable-stream-3.6.0"
            ];
          })
          (sources."string-width-4.2.0" // {
            dependencies = [
              sources."ansi-regex-5.0.0"
              sources."strip-ansi-6.0.0"
            ];
          })
          (sources."strip-ansi-0.3.0" // {
            dependencies = [
              sources."ansi-regex-4.1.0"
            ];
          })
          sources."strip-bom-3.0.0"
          sources."strip-json-comments-3.1.1"
          sources."through-2.3.8"
          sources."v8-compile-cache-2.1.1"
        ];
      })
      sources."plotly.js-basic-dist-1.53.0"
      sources."preact-10.3.4"
      sources."preact-router-3.2.1"
      sources."prop-types-15.7.2"
      sources."react-copy-to-clipboard-5.0.2"
      sources."react-is-16.13.1"
      sources."react-plotly.js-2.4.0"
      sources."react-redux-7.2.0"
      sources."redux-4.0.5"
      sources."redux-logger-3.0.6"
      sources."redux-thunk-2.3.0"
      sources."regenerator-runtime-0.13.5"
      sources."symbol-observable-1.2.0"
      sources."toggle-selection-1.0.6"
      sources."underscore-1.10.2"
      sources."url-polyfill-1.1.8"
      sources."zxcvbn-4.4.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  } // extraArgs;

  f = config:
    {
      tarball = nodeEnv.buildNodeSourceDist (args config);
      package = nodeEnv.buildNodePackage (args config);
      shell = nodeEnv.buildNodeShell (args config);
    };

in
  stdenv.lib.makeOverridable f {
    sources = rawSources;
    extraArgs = {};
  }
